#!/usr/bin/env node
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const websiteDir = resolve(scriptDir, "..");
const repoRoot = resolve(websiteDir, "..");
const docsRoot = join(websiteDir, "docs");
const manifestPath = join(websiteDir, "docs_manifest.json");
const indexPath = join(websiteDir, "docs_index.md");
const GENERATED_NOTE =
  "Generated by website/scripts/docs-index.mjs. Do not edit by hand.";

const STOP_WORDS = new Set([
  "about",
  "after",
  "agent",
  "also",
  "and",
  "are",
  "before",
  "build",
  "can",
  "for",
  "from",
  "guide",
  "hermes",
  "how",
  "into",
  "its",
  "the",
  "this",
  "through",
  "use",
  "using",
  "with",
  "you",
  "your",
]);

function toPosixPath(path) {
  return path.split(sep).join("/");
}

function walkDocs(dir) {
  if (!existsSync(dir)) {
    return [];
  }

  const entries = [];
  for (const name of readdirSync(dir).sort()) {
    const fullPath = join(dir, name);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      entries.push(...walkDocs(fullPath));
    } else if (/\.(md|mdx)$/.test(name)) {
      entries.push(fullPath);
    }
  }
  return entries;
}

function stripQuotes(value) {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function parseYamlValue(value) {
  const trimmed = value.trim();
  if (!trimmed) {
    return "";
  }
  if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
    return trimmed
      .slice(1, -1)
      .split(",")
      .map((item) => stripQuotes(item))
      .filter(Boolean);
  }
  if (/^(true|false)$/i.test(trimmed)) {
    return /^true$/i.test(trimmed);
  }
  if (/^-?\d+(\.\d+)?$/.test(trimmed)) {
    return Number(trimmed);
  }
  return stripQuotes(trimmed);
}

function parseFrontmatter(source) {
  if (!source.startsWith("---\n")) {
    return { frontmatter: {}, body: source };
  }

  const closeMatch = source.slice(4).match(/\n---\s*\n/);
  if (!closeMatch) {
    return { frontmatter: {}, body: source };
  }

  const frontmatterText = source.slice(4, closeMatch.index + 4);
  const body = source.slice(closeMatch.index + closeMatch[0].length + 4);
  const lines = frontmatterText.split(/\r?\n/);
  const frontmatter = {};

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (!line.trim() || line.trim().startsWith("#")) {
      continue;
    }

    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    if (rawValue.trim()) {
      frontmatter[key] = parseYamlValue(rawValue);
      continue;
    }

    const list = [];
    while (i + 1 < lines.length) {
      const next = lines[i + 1];
      const item = next.match(/^\s*-\s*(.+)$/);
      if (!item) {
        break;
      }
      list.push(stripQuotes(item[1]));
      i += 1;
    }
    frontmatter[key] = list.length > 0 ? list : "";
  }

  return { frontmatter, body };
}

function stripMarkdown(value) {
  return value
    .replace(/\{#[^}]+\}\s*$/g, "")
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[`*_~]/g, "")
    .replace(/<[^>]+>/g, "")
    .trim();
}

function extractHeadings(body) {
  const headings = [];
  let inFence = false;
  const lines = body.split(/\r?\n/);

  for (const line of lines) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) {
      continue;
    }

    const match = line.match(/^(#{1,6})\s+(.+)$/);
    if (!match) {
      continue;
    }
    headings.push({
      level: match[1].length,
      text: stripMarkdown(match[2]),
    });
  }

  return headings.filter((heading) => heading.text);
}

function titleFromPath(relativePath) {
  const basename = relativePath
    .replace(/^website\/docs\//, "")
    .replace(/\.(md|mdx)$/, "")
    .split("/")
    .pop();
  return basename
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function normalizeList(value) {
  if (Array.isArray(value)) {
    return value.map(String).map((item) => item.trim()).filter(Boolean);
  }
  if (typeof value === "string" && value.trim()) {
    return value
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  }
  return [];
}

function tokensFor(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .split(/\s+/)
    .filter((token) => token.length > 2 && !STOP_WORDS.has(token));
}

function buildKeywords({ relativePath, title, description, headings, frontmatter }) {
  const explicit = [
    ...normalizeList(frontmatter.keywords),
    ...normalizeList(frontmatter.tags),
  ];
  const derived = [
    ...tokensFor(relativePath.replace(/^website\/docs\//, "")),
    ...tokensFor(title),
    ...tokensFor(description),
    ...headings.flatMap((heading) => tokensFor(heading.text)),
  ];
  return [...new Set([...explicit, ...derived])].sort();
}

function docUrlFor(relativePath) {
  const slug = relativePath
    .replace(/^website\/docs\//, "")
    .replace(/\.(md|mdx)$/, "")
    .replace(/(^|\/)index$/, "");
  return `/docs/${slug}`.replace(/\/$/, "");
}

function readDocuments() {
  return walkDocs(docsRoot).map((filePath) => {
    const source = readFileSync(filePath, "utf8");
    const { frontmatter, body } = parseFrontmatter(source);
    const relativePath = toPosixPath(relative(repoRoot, filePath));
    const headings = extractHeadings(body);
    const title =
      typeof frontmatter.title === "string" && frontmatter.title.trim()
        ? frontmatter.title.trim()
        : headings.find((heading) => heading.level === 1)?.text ||
          titleFromPath(relativePath);
    const description =
      typeof frontmatter.description === "string"
        ? frontmatter.description.trim()
        : "";

    return {
      title,
      path: relativePath,
      url: docUrlFor(relativePath),
      description,
      headings,
      keywords: buildKeywords({
        relativePath,
        title,
        description,
        headings,
        frontmatter,
      }),
      frontmatter,
    };
  });
}

function writeManifest(documents) {
  const manifest = {
    schemaVersion: 1,
    note: GENERATED_NOTE,
    docsRoot: "website/docs",
    documentCount: documents.length,
    documents,
  };
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

function groupNameFor(doc) {
  return doc.path
    .replace(/^website\/docs\//, "")
    .split("/")
    .slice(0, -1)
    .join("/") || "root";
}

function writeMarkdownIndex(documents) {
  const byGroup = new Map();
  for (const doc of documents) {
    const group = groupNameFor(doc);
    if (!byGroup.has(group)) {
      byGroup.set(group, []);
    }
    byGroup.get(group).push(doc);
  }

  const lines = [
    "# Hermes Docs Index",
    "",
    `> ${GENERATED_NOTE}`,
    "",
    `Documents: ${documents.length}`,
    "",
    "Use `npm run docs:search -- <topic>` for ranked lookup. Ranking favors title, path, headings, description, and keywords before full text.",
    "",
  ];

  for (const group of [...byGroup.keys()].sort()) {
    lines.push(`## ${group}`, "");
    for (const doc of byGroup.get(group)) {
      const headings = doc.headings
        .filter((heading) => heading.level <= 3)
        .slice(0, 8)
        .map((heading) => heading.text)
        .join(" / ");
      const keywords = doc.keywords.slice(0, 16).join(", ");
      lines.push(`- [${doc.title}](${doc.path.replace(/^website\//, "")})`);
      lines.push(`  - path: \`${doc.path}\``);
      lines.push(`  - url: \`${doc.url}\``);
      if (doc.description) {
        lines.push(`  - description: ${doc.description}`);
      }
      if (headings) {
        lines.push(`  - headings: ${headings}`);
      }
      if (keywords) {
        lines.push(`  - keywords: ${keywords}`);
      }
    }
    lines.push("");
  }

  writeFileSync(indexPath, `${lines.join("\n").trimEnd()}\n`);
}

function generate() {
  mkdirSync(websiteDir, { recursive: true });
  const documents = readDocuments();
  writeManifest(documents);
  writeMarkdownIndex(documents);
  console.log(
    `[docs-index] indexed ${documents.length} docs into ${toPosixPath(
      relative(process.cwd(), manifestPath),
    )} and ${toPosixPath(relative(process.cwd(), indexPath))}`,
  );
}

function normalizedQuery(argv) {
  return argv.join(" ").trim().toLowerCase();
}

function scoreText(text, query, tokens, weight) {
  const normalized = String(text).toLowerCase();
  if (!normalized) {
    return 0;
  }

  let score = normalized.includes(query) ? weight * 4 : 0;
  for (const token of tokens) {
    if (normalized.includes(token)) {
      score += weight;
    }
  }
  return score;
}

function scoreSlug(path, query, tokens) {
  const basename = path
    .toLowerCase()
    .split("/")
    .pop()
    .replace(/\.(md|mdx)$/, "");
  let score = basename === query ? 250 : 0;
  for (const token of tokens) {
    if (basename === token) {
      score += 150;
    } else if (basename.split("-").includes(token)) {
      score += 30;
    }
  }
  return score;
}

function readBodyForSearch(doc) {
  const absolutePath = resolve(repoRoot, doc.path);
  if (!existsSync(absolutePath)) {
    return "";
  }
  return parseFrontmatter(readFileSync(absolutePath, "utf8")).body;
}

function search(argv) {
  let limit = 8;
  const terms = [];
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--limit" && argv[i + 1]) {
      limit = Number(argv[i + 1]) || limit;
      i += 1;
    } else {
      terms.push(argv[i]);
    }
  }

  const query = normalizedQuery(terms);
  if (!query) {
    console.error("Usage: node scripts/docs-index.mjs search <topic> [--limit 8]");
    process.exitCode = 2;
    return;
  }

  const documents = existsSync(manifestPath)
    ? JSON.parse(readFileSync(manifestPath, "utf8")).documents
    : readDocuments();
  const tokens = tokensFor(query);
  const scored = documents
    .map((doc) => {
      const fieldScores = {
        title: scoreText(doc.title, query, tokens, 50),
        path: scoreText(doc.path, query, tokens, 35),
        slug: scoreSlug(doc.path, query, tokens),
        headings: scoreText(
          doc.headings.map((heading) => heading.text).join(" "),
          query,
          tokens,
          20,
        ),
        description: scoreText(doc.description, query, tokens, 12),
        keywords: scoreText(doc.keywords.join(" "), query, tokens, 10),
      };
      const metadataScore = Object.values(fieldScores).reduce(
        (sum, value) => sum + value,
        0,
      );
      const bodyScore = scoreText(readBodyForSearch(doc), query, tokens, 1);
      const score = metadataScore + bodyScore;
      const matchedFields = Object.entries(fieldScores)
        .filter(([, value]) => value > 0)
        .map(([field]) => field);
      if (bodyScore > 0) {
        matchedFields.push("body");
      }
      return { doc, score, matchedFields };
    })
    .filter((result) => result.score > 0)
    .sort((a, b) => b.score - a.score || a.doc.path.localeCompare(b.doc.path))
    .slice(0, limit);

  if (scored.length === 0) {
    console.log(`No docs matched "${query}".`);
    return;
  }

  console.log(`Top docs for "${query}":`);
  scored.forEach(({ doc, score, matchedFields }, index) => {
    const matchingHeadings = doc.headings
      .filter((heading) => scoreText(heading.text, query, tokens, 1) > 0)
      .slice(0, 5)
      .map((heading) => heading.text);
    console.log(`${index + 1}. ${doc.title} [score ${score}]`);
    console.log(`   path: ${doc.path}`);
    console.log(`   url: ${doc.url}`);
    console.log(`   matched: ${matchedFields.join(", ")}`);
    if (doc.description) {
      console.log(`   description: ${doc.description}`);
    }
    if (matchingHeadings.length > 0) {
      console.log(`   headings: ${matchingHeadings.join(" / ")}`);
    }
  });
}

const [command = "generate", ...args] = process.argv.slice(2);

if (command === "generate") {
  generate();
} else if (command === "search") {
  search(args);
} else {
  console.error("Usage: node scripts/docs-index.mjs <generate|search> [args]");
  process.exitCode = 2;
}
